/opt/homebrew/Library/Homebrew/cmd/shellenv.sh: line 18: /bin/ps: Operation not permitted
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, FileText, Scale, Sparkles, UserRoundCheck } from "lucide-react";
import { processName, processOpportunity, useJ1Project } from "./j1Project";

const AXES = [
  { name: "Utilité", note: "La valeur métier et le niveau de répétition rendent-ils l’assistance utile ?", items: [["value", "Valeur ajoutée métier"], ["volume", "Répétitivité ou volume"]] },
  { name: "Capacité à agir", note: "Avons-nous les moyens de tester sans déplacer un risque non maîtrisé ?", items: [["feasibility", "Faisabilité technique"], ["dataRisk", "Risque lié aux données"]] },
  { name: "Impact humain", note: "Quel effet sur les personnes et sur la qualité de la relation RH ?", items: [["personImpact", "Impact sur les personnes"], ["relation", "Qualité de la relation RH"]] },
  { name: "Maîtrise", note: "Le projet est-il acceptable et le contrôle humain effectif ?", items: [["acceptance", "Acceptabilité sociale"], ["humanControl", "Possibilité de contrôle humain"]] },
];

function Field({ label, value, onChange, placeholder, area = false, hint }) {
  const Input = area ? "textarea" : "input";
  return <label className="ma-field"><span>{label}{hint && <small>{hint}</small>}</span><Input value={value || ""} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;
}

function Evaluation({ index, criterion, evaluation, update }) {
  return <article className="ma-evaluation"><div className="ma-evaluation-head"><div><span>PROCESSUS {index + 1}</span><h4>{processNamePlaceholder[index]}</h4></div><label className="ma-score"><span>Position 1–5</span><select value={evaluation.score || ""} onChange={(event) => update({ ...evaluation, score: event.target.value })}><option value="">Choisir</option>{[1, 2, 3, 4, 5].map((score) => <option key={score} value={score}>{score} — {score === 1 ? "très faible" : score === 5 ? "très élevé" : score === 3 ? "modéré" : score === 2 ? "faible" : "élevé"}</option>)}</select></label></div><Field area label="Justification" hint="Une à deux phrases, fondées sur la situation observée." value={evaluation.note} onChange={(value) => update({ ...evaluation, note: value })} placeholder={`Pourquoi « ${criterion} » est-il plutôt faible, modéré ou élevé ?`} /><div className="ma-evaluation-foot"><Field label="Information manquante" value={evaluation.missing} onChange={(value) => update({ ...evaluation, missing: value })} placeholder="Ex. validation DSI à confirmer" /><label className="ma-confidence"><span>Confiance dans cette appréciation</span><select value={evaluation.confidence || ""} onChange={(event) => update({ ...evaluation, confidence: event.target.value })}><option value="">À préciser</option><option>Faible</option><option>Moyenne</option><option>Élevée</option></select></label></div></article>;
}

// The process names are displayed by the parent; this small label keeps individual cards compact.
const processNamePlaceholder = ["Opportunité 1", "Opportunité 2"];

function PrintSummary({ project, averages }) {
  const arbitration = project.arbitration;
  const retained = arbitration.retained === "0" ? processName(project, 0) : arbitration.retained === "1" ? processName(project, 1) : "À décider";
  const deferred = arbitration.retained === "0" ? processName(project, 1) : arbitration.retained === "1" ? processName(project, 0) : "À décider";
  return <section className="print-summary"><h1>Arbitrage J1 — premier usage IA à instruire</h1><p><b>Usage retenu :</b> {retained}<br /><b>Usage différé ou écarté :</b> {deferred}</p><p><b>Justification :</b> {arbitration.rationale || "Non renseignée"}<br /><b>Informations à vérifier :</b> {arbitration.missingInformation || "—"}<br /><b>Décisionnaire :</b> {arbitration.decisionOwner || "—"}<br /><b>Prochaine étape :</b> {arbitration.nextStep || "—"}</p><h2>Repères chiffrés — ils éclairent le jugement, ils ne décident pas</h2>{[0, 1].map((index) => <p key={index}><b>{processName(project, index)}</b> : moyenne renseignée {averages[index] ?? "—"}/5. Opportunité : {processOpportunity(project, index)}</p>)}</section>;
}

export function ArbitrationMatrix({ back }) {
  const [project, setProject] = useJ1Project();
  const [step, setStep] = useState(0);
  const [saved, setSaved] = useState(false);
  const totalCriteria = AXES.flatMap((axis) => axis.items);
  const averages = useMemo(() => [0, 1].map((index) => {
    const values = totalCriteria.map(([id]) => Number(project.arbitration.evaluations?.[`${index}-${id}`]?.score)).filter(Boolean);
    return values.length ? (values.reduce((sum, item) => sum + item, 0) / values.length).toFixed(1) : null;
  }), [project, totalCriteria]);
  const updateEvaluation = (index, criterion, value) => setProject((current) => ({ ...current, arbitration: { ...current.arbitration, evaluations: { ...current.arbitration.evaluations, [`${index}-${criterion}`]: value } } }));
  const updateArbitration = (field, value) => setProject((current) => ({ ...current, arbitration: { ...current.arbitration, [field]: value } }));
  const stages = ["Comparer", "Décider", "Synthèse"];

  return <main className="ma-shell">
    <header className="ma-topbar"><button onClick={back}><ArrowLeft size={18} /> Retour à la journée 1</button><div><span><Scale size={17} /></span> Arbitre RH</div><p>Vos réponses sont sauvegardées sur cet appareil</p></header>
    <section className="ma-hero"><div><p>JOUR 1 · APRÈS-MIDI · DÉCIDER AVEC DISCERNEMENT</p><h1>Comparer avant <span>de retenir.</span></h1><p>Évaluez les deux opportunités selon huit critères. Les repères chiffrés structurent la discussion ; la décision reste humaine, argumentée et réversible.</p><div className="ma-pills"><span><Scale size={14} /> 4 angles · 8 critères</span><span><UserRoundCheck size={14} /> Aucun gagnant automatique</span><span><FileText size={14} /> Décision tracée</span></div></div><div className="ma-hero-summary"><small>OPPORTUNITÉS À COMPARER</small>{[0, 1].map((index) => <div key={index}><b>{String(index + 1).padStart(2, "0")}</b><span>{processName(project, index)}<em>{processOpportunity(project, index)}</em></span></div>)}</div></section>
    <div className="ma-layout"><aside className="ma-stepper"><p>PROGRESSION</p>{stages.map((label, index) => <button key={label} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => setStep(index)}><span>{index < step ? <Check size={14} /> : String(index + 1).padStart(2, "0")}</span>{label}</button>)}<div className="ma-note"><Sparkles size={15} /><p>Un score sans justification n’est pas un arbitrage.</p></div></aside>
      <section className="ma-workspace">{step === 0 && <><div className="ma-heading"><span>ÉTAPE 1 / 3</span><div><h2>Mettre les deux opportunités en regard</h2><p>Pour chaque critère, positionnez les deux processus de 1 à 5, expliquez votre appréciation et notez ce qui reste à vérifier.</p></div></div><div className="ma-scale"><b>Lecture des positions</b><span>1–2 : à sécuriser · 3 : à investiguer · 4–5 : plutôt favorable</span><em>Un risque de données élevé appelle une justification et des garde-fous ; il ne peut jamais être compensé mécaniquement.</em></div>{AXES.map((axis) => <section className="ma-axis" key={axis.name}><header><span>{axis.name}</span><p>{axis.note}</p></header>{axis.items.map(([id, label]) => <div className="ma-criterion" key={id}><h3>{label}</h3><div className="ma-compare-grid">{[0, 1].map((index) => <div key={index}><div className="ma-process-label"><b>{String(index + 1).padStart(2, "0")}</b><span>{processName(project, index)}</span></div><Evaluation index={index} criterion={label} evaluation={project.arbitration.evaluations?.[`${index}-${id}`] || {}} update={(value) => updateEvaluation(index, id, value)} /></div>)}</div></div>)}</section>)}</>}
        {step === 1 && <><div className="ma-heading"><span>ÉTAPE 2 / 3</span><div><h2>Assumer un premier choix</h2><p>Le choix du premier usage IA n’est pas celui qui a la moyenne la plus élevée : c’est celui que vous pouvez expliquer, sécuriser et tester.</p></div></div><div className="ma-scoreboard">{[0, 1].map((index) => <article key={index}><span>Processus {index + 1}</span><b>{processName(project, index)}</b><strong>{averages[index] ? `${averages[index]} / 5` : "À compléter"}</strong><p>{processOpportunity(project, index)}</p></article>)}</div><div className="ma-decision-card"><h3><CheckCircle2 size={18} /> Quelle opportunité retenez-vous en premier ?</h3><div className="ma-retained-choice">{[0, 1].map((index) => <button key={index} type="button" className={project.arbitration.retained === String(index) ? "selected" : ""} onClick={() => updateArbitration("retained", String(index))}><span>{project.arbitration.retained === String(index) && <Check size={14} />}</span><b>Retenir le processus {index + 1}</b><small>{processName(project, index)}</small></button>)}</div><Field area label="Justification du choix et du report" hint="Expliquez le processus retenu ET celui différé ou écarté." value={project.arbitration.rationale} onChange={(value) => updateArbitration("rationale", value)} placeholder="Ex. le premier processus offre une valeur immédiate avec des données moins sensibles ; le second est différé car son cadre d’accès reste à vérifier." /></div></>}
        {step === 2 && <><div className="ma-heading"><span>ÉTAPE 3 / 3</span><div><h2>Tracer la décision et la prochaine étape</h2><p>Une décision « pas maintenant » est utile lorsqu’elle est explicable, attribuée et suivie.</p></div></div><div className="ma-final-grid"><Field area label="Information(s) à vérifier" value={project.arbitration.missingInformation} onChange={(value) => updateArbitration("missingInformation", value)} placeholder="Ex. environnement autorisé, durée de conservation, validation DPO…" /><Field label="Qui porte la décision ?" value={project.arbitration.decisionOwner} onChange={(value) => updateArbitration("decisionOwner", value)} placeholder="Ex. DRH avec référent RGPD" /><Field area label="Prochaine étape concrète" value={project.arbitration.nextStep} onChange={(value) => updateArbitration("nextStep", value)} placeholder="Ex. confirmer le jeu de données fictif et préparer le test du lendemain." /></div><div className="ma-final-note"><CheckCircle2 size={19} /><div><b>Votre arbitre RH est prêt.</b><p>Le Feu tricolore des données va maintenant sécuriser le périmètre de l’usage retenu. Ensuite, le Studio C1 assemblera votre fiche et votre pitch de 2 minutes.</p></div></div></>}
        <div className="ma-actions"><button disabled={step === 0} onClick={() => setStep((current) => current - 1)}><ArrowLeft size={16} /> Précédent</button>{step < 2 ? <button className="ma-primary" onClick={() => setStep((current) => current + 1)}>Continuer <ArrowRight size={16} /></button> : <button className="ma-primary" onClick={() => { setSaved(true); window.print(); }}><FileText size={16} /> Exporter l’arbitrage</button>}</div>{saved && <p className="ma-saved"><CheckCircle2 size={16} /> Votre décision est prête à être imprimée ou enregistrée au format PDF.</p>}</section></div><PrintSummary project={project} averages={averages} />
  </main>;
}
