/opt/homebrew/Library/Homebrew/cmd/shellenv.sh: line 18: /bin/ps: Operation not permitted
import { useEffect, useMemo, useState } from "react";
import {
  AlarmClock, ArrowLeft, ArrowRight, Check, CheckCircle2, CircleAlert,
  FileCheck2, FileText, HeartHandshake, Lightbulb, Pause, Play,
  RefreshCw, ShieldCheck, Target, UsersRound,
} from "lucide-react";
import { processName, processOpportunity, useJ1Project } from "./j1Project";

const STEPS = [
  ["Choix", FileCheck2, "Relier le contexte, les deux processus et l’arbitrage."],
  ["Sécuriser", ShieldCheck, "Documenter les risques, mesures de prévention et vérifications."],
  ["Prouver", Target, "Formuler un objectif mesurable et une baseline utilisable."],
  ["Délimiter", CircleAlert, "Rendre le périmètre, les exclusions et le passage à J2 explicites."],
  ["Présenter", UsersRound, "Préparer et tester une présentation de 2 minutes."],
];

function Field({ label, hint, value, onChange, placeholder, area = false }) {
  const Input = area ? "textarea" : "input";
  return <label className="c1-field"><span>{label}{hint && <small>{hint}</small>}</span><Input value={value || ""} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;
}

function ChoiceView({ project }) {
  const retained = project.arbitration.retained === "0" || project.arbitration.retained === "1" ? Number(project.arbitration.retained) : null;
  const deferred = retained === 0 ? 1 : retained === 1 ? 0 : null;
  return <div className="c1-choice"><div className="c1-context-card"><span><Lightbulb size={20} /></span><div><p>CONTEXTE OBSERVÉ</p><h3>{project.context.organisation || "Votre organisation"}</h3><b>{project.context.role || "Rôle à préciser"}</b><p>{project.context.irritant || "Décrivez l’irritant dans le Cartographe des opportunités RH."}</p></div></div><div className="c1-compare"><article className={retained === 0 ? "retained" : ""}><small>PROCESSUS 01 {retained === 0 && "· RETENU"}</small><h3>{processName(project, 0)}</h3><p>{processOpportunity(project, 0)}</p></article><article className={retained === 1 ? "retained" : ""}><small>PROCESSUS 02 {retained === 1 && "· RETENU"}</small><h3>{processName(project, 1)}</h3><p>{processOpportunity(project, 1)}</p></article></div><div className="c1-decision-read"><b>Usage retenu</b><span>{retained !== null ? `${processName(project, retained)} — ${processOpportunity(project, retained)}` : "À choisir dans l’Arbitre RH"}</span><b>Usage différé ou écarté</b><span>{deferred !== null ? processName(project, deferred) : "À préciser"}</span><b>Justification de l’arbitrage</b><span>{project.arbitration.rationale || "À documenter dans l’Arbitre RH"}</span></div></div>;
}

function SecurityView({ c1, update, project }) {
  const trafficFlags = Object.entries(project.traffic.axes || {}).filter(([, value]) => value.level === "orange" || value.level === "red").map(([id, value]) => `${id} : ${value.reason || "à vérifier"}`);
  return <div className="c1-form-stack"><div className="c1-traffic-link"><ShieldCheck size={18} /><div><b>Apport du Feu tricolore</b><p>{trafficFlags.length ? trafficFlags.join(" · ") : "Aucun axe orange ou rouge n’est encore déclaré — vérifiez néanmoins les six axes dans le Feu tricolore."}</p></div></div><div className="c1-risk-grid"><article><h3>Risque éthique ou juridique 1</h3><Field area label="Risque identifié" value={c1.ethicalRisk1} onChange={(value) => update("ethicalRisk1", value)} placeholder="Ex. une formulation peut introduire un biais ou une discrimination." /><Field area label="Mesure de prévention" value={c1.ethicalPrevention1} onChange={(value) => update("ethicalPrevention1", value)} placeholder="Ex. relecture inclusive et validation RH avant diffusion." /></article><article><h3>Risque éthique ou juridique 2</h3><Field area label="Risque identifié" value={c1.ethicalRisk2} onChange={(value) => update("ethicalRisk2", value)} placeholder="Ex. donnée non nécessaire ou environnement non autorisé." /><Field area label="Mesure de prévention" value={c1.ethicalPrevention2} onChange={(value) => update("ethicalPrevention2", value)} placeholder="Ex. retirer la donnée ou consulter le DPO avant test." /></article></div><div className="c1-risk-grid relational"><article><h3><HeartHandshake size={17} /> Risque relationnel</h3><Field area label="Effet possible sur la relation RH" value={c1.relationalRisk} onChange={(value) => update("relationalRisk", value)} placeholder="Ex. impression de déshumanisation ou perte de confiance dans la réponse RH." /><Field area label="Ce qui préserve la relation" value={c1.relationalPrevention} onChange={(value) => update("relationalPrevention", value)} placeholder="Ex. une personne nommée relit, explique et reste joignable." /></article></div><div className="c1-grid two"><Field label="Référence / source à mobiliser 1" value={c1.legalReference1} onChange={(value) => update("legalReference1", value)} placeholder="Ex. politique interne IA, RGPD, guide CNIL" /><Field label="Référence / source à mobiliser 2" value={c1.legalReference2} onChange={(value) => update("legalReference2", value)} placeholder="Ex. procédure DPO, charte informatique" /><Field area label="Questions à faire vérifier" value={c1.questionsToVerify} onChange={(value) => update("questionsToVerify", value)} placeholder="Ex. quel outil est autorisé ? quelle durée de conservation ?" /></div></div>;
}

function ProofView({ c1, update }) {
  return <div className="c1-form-stack"><div className="c1-objective"><Target size={21} /><div><h3>Un objectif ne se démontre que par une mesure.</h3><p>La baseline est la valeur observée avant le projet. Elle ne se confond ni avec la cible, ni avec la solution choisie.</p></div></div><div className="c1-grid two"><Field area label="Objectif mesurable" value={c1.indicator} onChange={(value) => update("indicator", value)} placeholder="Ex. réduire le temps de production du premier brouillon sans dégrader la qualité." /><Field label="Baseline initiale" value={c1.baseline} onChange={(value) => update("baseline", value)} placeholder="Ex. 40 min par offre" /><Field label="Méthode, date et source de la baseline" value={c1.baselineMethod} onChange={(value) => update("baselineMethod", value)} placeholder="Ex. moyenne de 10 offres, relevée le 10/09 par l’équipe RH" /><Field label="Cible" value={c1.target} onChange={(value) => update("target", value)} placeholder="Ex. 30 min par offre" /><Field label="Horizon" value={c1.horizon} onChange={(value) => update("horizon", value)} placeholder="Ex. 4 semaines de pilote" /><Field label="Responsable du suivi" value={c1.responsible} onChange={(value) => update("responsible", value)} placeholder="Ex. responsable recrutement" /></div></div>;
}

function ScopeView({ c1, update }) {
  return <div className="c1-form-stack"><div className="c1-scope-grid"><article className="in"><CheckCircle2 size={20} /><h3>Dans le périmètre</h3><Field area label="Tâches assistées et données autorisées" value={c1.included} onChange={(value) => update("included", value)} placeholder="Ex. premier brouillon à partir d’une fiche de poste validée ; utilisation de sources fictives ou autorisées." /><Field area label="Données explicitement autorisées" value={c1.allowedData} onChange={(value) => update("allowedData", value)} placeholder="Ex. référentiel métier, modèle d’offre, procédures validées." /></article><article className="out"><CircleAlert size={20} /><h3>Hors périmètre</h3><Field area label="Décisions, cas ou données exclus" value={c1.excluded} onChange={(value) => update("excluded", value)} placeholder="Ex. tri de CV, décision de recrutement, données de santé, publication automatique." /><Field area label="Cas particuliers et règle d’escalade" value={c1.specialCases} onChange={(value) => update("specialCases", value)} placeholder="Ex. cas sensible transmis au responsable RH ou au DPO avant toute utilisation." /></article></div><div className="c1-grid two"><Field label="Qui valide humainement ?" value={c1.humanValidation} onChange={(value) => update("humanValidation", value)} placeholder="Ex. responsable recrutement avant diffusion" /><Field area label="Question à instruire au jour 2" value={c1.j2Question} onChange={(value) => update("j2Question", value)} placeholder="Ex. quel prompt de production et quel prompt de contrôle tester avec des données fictives ?" /></div></div>;
}

function formatTime(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

function PitchView({ c1, update, project }) {
  const [seconds, setSeconds] = useState(120);
  const [running, setRunning] = useState(false);
  useEffect(() => { if (!running) return undefined; const timer = window.setInterval(() => setSeconds((current) => { if (current <= 1) { window.clearInterval(timer); setRunning(false); return 0; } return current - 1; }), 1000); return () => window.clearInterval(timer); }, [running]);
  const retained = project.arbitration.retained === "0" || project.arbitration.retained === "1" ? Number(project.arbitration.retained) : null;
  const deferred = retained === 0 ? 1 : retained === 1 ? 0 : null;
  const outline = useMemo(() => [
    ["1", "Le besoin réel", project.context.irritant || "Irritant à formuler"],
    ["2", "Le processus retenu", retained !== null ? processName(project, retained) : "À choisir"],
    ["3", "L’opportunité principale", retained !== null ? processOpportunity(project, retained) : "À formuler"],
    ["4", "Ce que vous différez", deferred !== null ? processName(project, deferred) : "À préciser"],
    ["5", "Le risque majeur", c1.ethicalRisk1 || c1.relationalRisk || "À documenter"],
    ["6", "Le garde-fou", c1.ethicalPrevention1 || c1.humanValidation || "À documenter"],
    ["7", "L’objectif", c1.indicator || "À formuler"],
    ["8", "La baseline", c1.baseline || "À mesurer"],
    ["9", "La prochaine vérification", c1.questionsToVerify || c1.j2Question || "À préciser"],
  ], [c1, deferred, project, retained]);
  return <div className="c1-pitch"><div className="c1-pitch-top"><div><p>PITCH J1 · 2 MINUTES</p><h3>Présenter un projet crédible, pas une solution parfaite.</h3><span>La trame assume le choix, les limites, les garde-fous et la prochaine décision humaine.</span></div><div className="c1-timer"><strong>{formatTime(seconds)}</strong><div><button onClick={() => { if (seconds === 0) setSeconds(120); setRunning((value) => !value); }}>{running ? <Pause size={15} /> : <Play size={15} />} {running ? "Pause" : seconds === 0 ? "Rejouer" : "Lancer"}</button><button onClick={() => { setRunning(false); setSeconds(120); }}><RefreshCw size={15} /> Réinitialiser</button></div></div></div><div className="c1-outline">{outline.map(([number, title, copy]) => <article key={number}><span>{number}</span><div><b>{title}</b><p>{copy}</p></div></article>)}</div><Field area label="Vos mots de liaison ou notes de pitch" value={c1.pitchNotes} onChange={(value) => update("pitchNotes", value)} placeholder="Ajoutez ici les transitions qui rendent votre récit naturel. L’objectif n’est pas de réciter une formule automatique." /><div className="c1-peer"><h3><UsersRound size={18} /> Retour d’un autre participant</h3><Field area label="Question reçue" value={c1.peerQuestion} onChange={(value) => update("peerQuestion", value)} placeholder="Ex. comment vérifiez-vous que la relecture ne dégrade pas le gain de temps ?" /><p>Évaluation rapide</p><div>{[["clear", "Clair"], ["clarify", "À préciser"], ["secure", "À sécuriser"]].map(([value, label]) => <button type="button" key={value} className={c1.feedback === value ? "selected" : ""} onClick={() => update("feedback", value)}>{c1.feedback === value && <Check size={14} />}{label}</button>)}</div><Field area label="Correction décidée avant de sauvegarder la fiche C1" value={c1.correction} onChange={(value) => update("correction", value)} placeholder="Ex. préciser la donnée de départ et nommer le validateur humain." /></div></div>;
}

function PrintSummary({ project }) {
  const c1 = project.c1; const retained = project.arbitration.retained === "0" || project.arbitration.retained === "1" ? Number(project.arbitration.retained) : null;
  return <section className="print-summary"><h1>Fiche C1 — Cadrer et présenter son projet IA & RH</h1><h2>Contexte et choix</h2><p><b>Organisation :</b> {project.context.organisation || "—"}<br /><b>Irritant :</b> {project.context.irritant || "—"}<br /><b>Processus retenu :</b> {retained !== null ? processName(project, retained) : "—"}<br /><b>Opportunité :</b> {retained !== null ? processOpportunity(project, retained) : "—"}<br /><b>Arbitrage :</b> {project.arbitration.rationale || "—"}</p><h2>Sécurisation</h2><p><b>Risque 1 / prévention :</b> {c1.ethicalRisk1 || "—"} / {c1.ethicalPrevention1 || "—"}<br /><b>Risque 2 / prévention :</b> {c1.ethicalRisk2 || "—"} / {c1.ethicalPrevention2 || "—"}<br /><b>Risque relationnel / préservation :</b> {c1.relationalRisk || "—"} / {c1.relationalPrevention || "—"}<br /><b>Références :</b> {[c1.legalReference1, c1.legalReference2].filter(Boolean).join(" · ") || "—"}<br /><b>À vérifier :</b> {c1.questionsToVerify || "—"}</p><h2>Objectif et mesure</h2><p><b>Objectif :</b> {c1.indicator || "—"}<br /><b>Baseline :</b> {c1.baseline || "—"}<br /><b>Méthode/date/source :</b> {c1.baselineMethod || "—"}<br /><b>Cible / horizon :</b> {c1.target || "—"} / {c1.horizon || "—"}<br /><b>Responsable :</b> {c1.responsible || "—"}</p><h2>Périmètre et passage à J2</h2><p><b>Inclus :</b> {c1.included || "—"}<br /><b>Données autorisées :</b> {c1.allowedData || "—"}<br /><b>Exclus :</b> {c1.excluded || "—"}<br /><b>Validation humaine :</b> {c1.humanValidation || "—"}<br /><b>Question J2 :</b> {c1.j2Question || "—"}</p><h2>Retour sur le pitch</h2><p><b>Question reçue :</b> {c1.peerQuestion || "—"}<br /><b>Évaluation :</b> {c1.feedback || "—"}<br /><b>Correction :</b> {c1.correction || "—"}</p></section>;
}

export function C1Studio({ back }) {
  const [project, setProject] = useJ1Project();
  const [step, setStep] = useState(0);
  const [saved, setSaved] = useState(false);
  const c1 = project.c1;
  const update = (field, value) => setProject((current) => ({ ...current, c1: { ...current.c1, [field]: value } }));
  return <main className="c1-shell"><header className="c1-topbar"><button onClick={back}><ArrowLeft size={18} /> Retour à la journée 1</button><div><span><FileCheck2 size={17} /></span> Studio C1</div><p>Fiche finale et pitch de 2 minutes</p></header><section className="c1-hero"><div><p>JOUR 1 · CADRER ET PRÉSENTER</p><h1>Votre projet, <span>en une fiche défendable.</span></h1><p>Assemblez les éléments produits pendant la journée, précisez les preuves manquantes et préparez un pitch réaliste de deux minutes.</p><div className="c1-pills"><span><FileText size={14} /> Données reprises automatiquement</span><span><ShieldCheck size={14} /> Limites documentées</span><span><UsersRound size={14} /> Pair feedback intégré</span></div></div><div className="c1-hero-card"><span>FICHE C1</span><b>Un projet limité,<br />mesurable et humain.</b><small>À compléter, corriger et exporter.</small></div></section><section className="c1-layout"><aside className="c1-stepper"><p>PROGRESSION</p>{STEPS.map(([label, Icon], index) => <button key={label} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => setStep(index)}><span>{index < step ? <Check size={14} /> : <Icon size={15} />}</span><b>{String(index + 1).padStart(2, "0")}</b>{label}</button>)}<div className="c1-mini"><FileText size={15} /><p>Les champs restent modifiables jusqu’à l’export final.</p></div></aside><section className="c1-workspace"><div className="c1-heading"><span>ÉTAPE {step + 1} / {STEPS.length}</span><div><h2>{STEPS[step][0]}</h2><p>{STEPS[step][2]}</p></div></div>{step === 0 && <ChoiceView project={project} />}{step === 1 && <SecurityView c1={c1} update={update} project={project} />}{step === 2 && <ProofView c1={c1} update={update} />}{step === 3 && <ScopeView c1={c1} update={update} />}{step === 4 && <PitchView c1={c1} update={update} project={project} />}<div className="c1-actions"><button disabled={step === 0} onClick={() => setStep((current) => current - 1)}><ArrowLeft size={16} /> Précédent</button>{step < STEPS.length - 1 ? <button className="c1-primary" onClick={() => setStep((current) => current + 1)}>Continuer <ArrowRight size={16} /></button> : <button className="c1-primary" onClick={() => { setSaved(true); window.print(); }}><FileText size={16} /> Exporter la fiche C1</button>}</div>{saved && <p className="c1-saved"><CheckCircle2 size={16} /> Votre fiche C1 est prête à être enregistrée au format PDF.</p>}</section></section><PrintSummary project={project} /></main>;
}
