/opt/homebrew/Library/Homebrew/cmd/shellenv.sh: line 18: /bin/ps: Operation not permitted
import { useMemo, useState } from "react";
import {
  AlertTriangle, Archive, ArrowLeft, ArrowRight, Check, CheckCircle2,
  Database, Eye, FileText, KeyRound, Printer, RefreshCw, ShieldCheck,
  Target, UserCheck, XCircle,
} from "lucide-react";
import { processName, processOpportunity, useJ1Project } from "./j1Project";

const AXES = [
  { id: "purpose", label: "Finalité précise", icon: Target, help: "Délimitez le traitement : une tâche, un résultat attendu, une finalité expliquable.", prompt: "Ex. générer un premier brouillon d’offre à partir d’une fiche de poste validée, sans données de candidats." },
  { id: "minimization", label: "Minimisation", icon: Database, help: "N’utilisez que les données nécessaires. Nommer ce qui est exclu est une mesure de protection.", prompt: "Ex. fiche de poste et référentiel métier seulement ; CV, rémunération et évaluations exclus." },
  { id: "access", label: "Accès et permissions", icon: KeyRound, help: "Qui peut accéder aux données, les consulter, les corriger ou les valider ?", prompt: "Ex. équipe recrutement autorisée ; droits d’accès vérifiés avec la DSI." },
  { id: "environment", label: "Environnement autorisé", icon: ShieldCheck, help: "L’outil et son cadre d’usage doivent être identifiés et autorisés par l’organisation.", prompt: "Ex. environnement IA organisationnel validé ; aucun copier-coller dans un outil public." },
  { id: "conservation", label: "Conservation", icon: Archive, help: "Préparez la durée, le lieu de conservation et la suppression des éléments de test.", prompt: "Ex. brouillons conservés dans le dossier RH validé ; données de test supprimées après la revue." },
  { id: "human", label: "Validation humaine et hors périmètre", icon: UserCheck, help: "L’IA assiste ; une personne identifiée relit, décide et laisse une trace. Les décisions sur les personnes restent hors périmètre.", prompt: "Ex. validation par le responsable recrutement ; tri de CV et décision de recrutement explicitement exclus." },
];

function Field({ label, hint, value, onChange, placeholder, area = false }) {
  const Input = area ? "textarea" : "input";
  return <label className="dt-field"><span>{label}{hint && <small>{hint}</small>}</span><Input value={value || ""} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;
}

function AxisForm({ axis, value, update }) {
  const Icon = axis.icon;
  return <div className="dt-axis-form"><div className="dt-axis-intro"><span><Icon size={20} /></span><div><h2>{axis.label}</h2><p>{axis.help}</p></div></div><Field area label="Ce que vous avez vérifié / délimité" value={value.detail} onChange={(detail) => update({ ...value, detail })} placeholder={axis.prompt} /><div className="dt-level"><p>Niveau de maîtrise sur cet axe</p><div>{[["green", "Vert", "Condition maîtrisée"], ["orange", "Orange", "À vérifier ou à limiter"], ["red", "Rouge", "Bloquant en l’état"]].map(([level, label, text]) => <button type="button" key={level} className={`${level} ${value.level === level ? "selected" : ""}`} onClick={() => update({ ...value, level })}><i>{value.level === level && <Check size={12} />}</i><b>{label}</b><span>{text}</span></button>)}</div></div>{value.level === "red" && <div className="dt-alert"><XCircle size={18} /><div><b>Critère rouge : il ne peut pas être compensé par les autres axes.</b><p>Le périmètre doit être retiré, limité ou revu avant tout test.</p></div></div>}<div className="dt-grid two"><Field area label="Raison du classement" value={value.reason} onChange={(reason) => update({ ...value, reason })} placeholder="Pourquoi est-ce maîtrisé, à vérifier ou bloquant ?" /><Field area label="Mesure de prévention / correction" value={value.prevention} onChange={(prevention) => update({ ...value, prevention })} placeholder="Ex. retirer la donnée, demander une validation, utiliser une version fictive." /><Field label="Personne à consulter ou responsable" value={value.owner} onChange={(owner) => update({ ...value, owner })} placeholder="Ex. DPO, DSI, responsable RH" /><Field label="Point de contrôle" value={value.checkpoint} onChange={(checkpoint) => update({ ...value, checkpoint })} placeholder="Ex. avant le test pilote du 12 septembre" /></div></div>;
}

function Result({ project, status, goBack, reset }) {
  const traffic = project.traffic;
  const retainedIndex = traffic.selected ?? project.arbitration.retained;
  const selected = retainedIndex === "0" || retainedIndex === "1" ? Number(retainedIndex) : null;
  const meta = { green: ["green", CheckCircle2, "Poursuivre dans le périmètre déclaré"], orange: ["orange", AlertTriangle, "Limiter et vérifier avant test"], red: ["red", XCircle, "Différer ou revoir le périmètre"], incomplete: ["gray", AlertTriangle, "Analyse à compléter"] }[status];
  const [color, Icon, title] = meta;
  return <div className="dt-result-wrap"><section className="dt-result"><div className="dt-result-head"><div className="dt-light"><i className={status === "red" ? "on red" : "red"} /><i className={status === "orange" ? "on orange" : "orange"} /><i className={status === "green" ? "on green" : "green"} /></div><div className={`dt-status ${color}`}><Icon size={25} /><div><span>Décision pédagogique provisoire</span><h2>{title}</h2><p>{status === "red" ? "Au moins un critère rouge exige de suspendre ou de modifier l’usage." : status === "orange" ? "Le projet reste possible uniquement après les vérifications et corrections identifiées." : status === "green" ? "Les six conditions déclarées sont maîtrisées. Le contrôle humain reste obligatoire." : "Renseignez les six axes pour produire une décision utilisable."}</p></div></div></div><div className="dt-disclaimer"><ShieldCheck size={15} /> Cet outil aide à cadrer un atelier ou un pilote. Il ne constitue ni une validation juridique ni un avis de conformité RGPD.</div><div className="dt-result-context"><b>Usage analysé</b><span>{selected !== null ? `${processName(project, selected)} — ${processOpportunity(project, selected)}` : "Choisissez d’abord un processus dans l’Arbitre RH, ou renseignez les six axes pour documenter le cas."}</span></div><div className="dt-axis-summary">{AXES.map((axis) => { const item = traffic.axes?.[axis.id] || {}; const AxisIcon = axis.icon; return <article key={axis.id} className={item.level || "gray"}><header><span><AxisIcon size={16} /></span><div><b>{axis.label}</b><em>{item.level === "green" ? "Vert · maîtrisé" : item.level === "orange" ? "Orange · à vérifier" : item.level === "red" ? "Rouge · bloquant" : "À compléter"}</em></div></header><p>{item.detail || "Non renseigné"}</p><dl><div><dt>Raison</dt><dd>{item.reason || "—"}</dd></div><div><dt>Prévention</dt><dd>{item.prevention || "—"}</dd></div><div><dt>Responsable / point de contrôle</dt><dd>{[item.owner, item.checkpoint].filter(Boolean).join(" · ") || "—"}</dd></div></dl></article>})}</div><Field area label="Formulation courte pour la fiche C1" hint="Cette phrase est conservée par le Studio C1 avec le reste du dossier." value={traffic.summary} onChange={() => {}} placeholder="" /><div className="dt-result-actions"><button onClick={goBack}><ArrowLeft size={15} /> Modifier l’analyse</button><button onClick={reset}><RefreshCw size={15} /> Réinitialiser</button><button className="dt-primary" onClick={() => window.print()}><Printer size={15} /> Exporter / imprimer</button></div></section></div>;
}

function PrintSummary({ project, status }) {
  const traffic = project.traffic;
  return <section className="print-summary"><h1>Feu tricolore des données — J1</h1><p><b>Décision provisoire :</b> {status === "green" ? "Poursuivre dans le périmètre déclaré" : status === "orange" ? "Limiter et vérifier" : status === "red" ? "Différer ou revoir le périmètre" : "À compléter"}</p>{AXES.map((axis) => { const item = traffic.axes?.[axis.id] || {}; return <div key={axis.id}><h2>{axis.label} — {item.level || "à compléter"}</h2><p>{item.detail || "—"}<br /><b>Raison :</b> {item.reason || "—"}<br /><b>Prévention :</b> {item.prevention || "—"}<br /><b>Responsable / point de contrôle :</b> {[item.owner, item.checkpoint].filter(Boolean).join(" · ") || "—"}</p></div>})}<p><b>Formulation C1 :</b> {traffic.summary || "—"}</p></section>;
}

export function DataTrafficLight({ back }) {
  const [project, setProject] = useJ1Project();
  const [step, setStep] = useState(0);
  const values = AXES.map((axis) => project.traffic.axes?.[axis.id] || {});
  const completed = values.filter((item) => item.detail && item.level).length;
  const status = useMemo(() => completed < AXES.length ? "incomplete" : values.some((item) => item.level === "red") ? "red" : values.some((item) => item.level === "orange") ? "orange" : "green", [completed, values]);
  const updateAxis = (axisId, value) => setProject((current) => ({ ...current, traffic: { ...current.traffic, axes: { ...current.traffic.axes, [axisId]: value } } }));
  const reset = () => setProject((current) => ({ ...current, traffic: { axes: {}, decision: "", summary: "" } }));
  const current = AXES[step];
  const generateSummary = () => {
    const selected = project.arbitration.retained === "0" || project.arbitration.retained === "1" ? Number(project.arbitration.retained) : null;
    const decision = status === "green" ? "peut être poursuivi dans le périmètre déclaré" : status === "orange" ? "doit être limité et vérifié avant tout test" : status === "red" ? "doit être différé ou redéfini avant tout test" : "reste à compléter";
    const green = AXES.filter((axis) => project.traffic.axes?.[axis.id]?.level === "green").map((axis) => axis.label.toLowerCase()).join(", ") || "à préciser";
    return `L’usage « ${selected !== null ? processOpportunity(project, selected) : "à préciser"} » ${decision}. Les conditions maîtrisées sont : ${green}. Les écarts, mesures de prévention et responsables sont documentés dans le Feu tricolore ; toute décision RH demeure humaine et les usages hors périmètre sont exclus.`;
  };
  return <main className="dt-shell"><header className="dt-topbar"><button onClick={back}><ArrowLeft size={17} /> Retour à la journée 1</button><div><span><ShieldCheck size={17} /></span> Feu tricolore des données</div><button onClick={reset}><RefreshCw size={15} /> Réinitialiser</button></header><section className="dt-hero"><div><p>JOUR 1 · SÉCURISER AVANT DE TESTER</p><h1>Feu tricolore <span>des données.</span></h1><p>Examinez le périmètre de l’usage retenu selon six conditions simples. Un critère rouge reste bloquant, quels que soient les autres résultats.</p><div className="dt-pills"><span><ShieldCheck size={14} /> Outil pédagogique, non juridique</span><span><Database size={14} /> 6 axes de vérification</span><span><UserCheck size={14} /> Décision humaine maintenue</span></div></div><div className="dt-hero-light"><i /><i /><i /></div></section>{step < AXES.length ? <div className="dt-layout"><aside className="dt-stepper"><p>PROGRESSION</p>{AXES.map((axis, index) => { const Icon = axis.icon; return <button key={axis.id} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => setStep(index)}><span>{index < step ? <Check size={13} /> : <Icon size={14} />}</span><b>{String(index + 1).padStart(2, "0")}</b>{axis.label}</button>; })}<div className="dt-mini"><i className={status} /><span>{completed}/{AXES.length} axes renseignés</span></div></aside><section className="dt-workspace"><div className="dt-heading"><span>ÉTAPE {step + 1} / {AXES.length}</span><div><h2>{current.label}</h2><p>{current.help}</p></div></div><AxisForm axis={current} value={project.traffic.axes?.[current.id] || {}} update={(value) => updateAxis(current.id, value)} /><div className="dt-actions"><button disabled={step === 0} onClick={() => setStep((currentStep) => currentStep - 1)}><ArrowLeft size={16} /> Précédent</button>{step < AXES.length - 1 ? <button className="dt-primary" onClick={() => setStep((currentStep) => currentStep + 1)}>Continuer <ArrowRight size={16} /></button> : <button className="dt-primary" onClick={() => { setProject((currentProject) => ({ ...currentProject, traffic: { ...currentProject.traffic, summary: generateSummary() } })); setStep(AXES.length); }}><FileText size={16} /> Voir la synthèse</button>}</div></section></div> : <Result project={project} status={status} goBack={() => setStep(AXES.length - 1)} reset={() => { reset(); setStep(0); }} />}<PrintSummary project={project} status={status} /></main>;
}
